version: 0.2 

phases: 
  build:
    commands:
      - echo entered the build phases
      - gradle clean
  post_build:
    commands:
      - echo build completed successfully
artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes